# Generated by Django 5.1.3 on 2024-12-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_article_category_alter_article_imgurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdfUrlDownload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pdfUrlView',
            field=models.TextField(blank=True, null=True),
        ),
    ]
