# Generated by Django 5.1.3 on 2024-12-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_article_magazin_article_puplished_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdfID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
