# Generated by Django 5.1.3 on 2025-01-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_youtubevideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='resume',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
