# Generated by Django 5.1.3 on 2025-01-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_article_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='readCount',
            field=models.IntegerField(default=0),
        ),
    ]
