# Generated by Django 5.1.3 on 2025-01-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_article_readcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='downloadCount',
            field=models.IntegerField(default=0),
        ),
    ]
