# Generated by Django 5.1.3 on 2025-01-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_message_sentto'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
