# Generated by Django 5.1.3 on 2025-01-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='books_actually_borrwed',
            field=models.ManyToManyField(blank=True, null=True, related_name='borrwed_now', to='website.book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='books_added',
            field=models.ManyToManyField(blank=True, null=True, related_name='added_by', to='website.book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='books_borrwed',
            field=models.ManyToManyField(blank=True, null=True, related_name='borrwed_by', to='website.book'),
        ),
    ]
