# Generated by Django 5.1.3 on 2025-01-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_profile_books_actually_borrwed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.IntegerField(null=True),
        ),
    ]
